#!/usr/bin/env python
"""
Bootloader Build Tool

This tool is responsible for building the bootloader from source and copying
the build outputs into the host tools directory for programming.
"""
import os
import random
import shutil
import subprocess
import sys

from intelhex import IntelHex

FILE_DIR = os.path.abspath(os.path.dirname(__file__))

def make_bootloader(password=None):
    """
    Build the bootloader from source.

    Return:
        True if successful, False otherwise.
    """
    # Change into directory containing bootloader.
    os.chdir('../bootloader')

    subprocess.call('make clean', shell=True)
    # Call make in subprocess to build bootloader.
    if password is not None:
        status = subprocess.call('make PASSWORD="%s"' % password, shell=True)
    else:
        status = subprocess.call('make')

    # Return True if make returned 0, otherwise return False.
    return (status == 0)

def copy_artifacts():
    """
    Copy bootloader build artifacts into the host tools directory.
    """
    # Get directory containing this file (host_tools).
    dst_dir = FILE_DIR

    # Get directory containing bootloader output (bootloader).
    src_dir = os.path.join(os.path.dirname(dst_dir), 'bootloader')

    # Copy build artifacts from bootloader directory.
    shutil.copy(os.path.join(src_dir, 'flash.hex'), dst_dir)
    shutil.copy(os.path.join(src_dir, 'eeprom.hex'), dst_dir)

def generate_readback_password():
    """
    Generate secret password for readback tool and store to secret file.
    """
    # Generate 16 character random password.
    pw = ''.join(chr(random.randint(0, 255)) for i in range(8)).encode('hex')

    # Write password to secret file.
    with open('secret_build_output.txt', 'wb+') as secret_build_output:
        secret_build_output.write(pw)

    return pw

def write_fuse_file(fuse_name, fuse_value):
    hex_file = IntelHex()
    hex_file[0] = fuse_value

    with open(os.path.join(FILE_DIR, fuse_name + '.hex'), 'wb+') as outfile:
        hex_file.tofile(outfile, format='hex')

if __name__ == '__main__':
    password = generate_readback_password()
    if not make_bootloader(password=password):
        print "ERROR: Failed to compile bootloader."
        sys.exit(1)
    copy_artifacts()
    write_fuse_file('lfuse', 0xCE)
    write_fuse_file('hfuse', 0x18)
    write_fuse_file('efuse', 0xFF)

